variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/sel
  tags: ["kubernetes", "cluster"]
  before_script:
    - cp -r $(pwd)/ /root/quicklisp/local-projects/

check-format:
  stage: .pre
  script:
    - git lisp-format

build-manual:
  stage: test
  script:
    - GT=yes make doc

.test-template: &test
  stage: test
  script:
    - LISP=$LISP GT=yes make check

test-sbcl:
  variables:
    LISP: 'sbcl'
  <<: *test

test-ccl:
  variables:
    LISP: 'ccl'
  <<: *test

binary-release:
  stage: deploy
  artifacts:
    paths:
      - resolve
  script:
    - sbcl --script build.lisp && ccl --load build.lisp
    - mv build resolve
  only:
    - master

dependents:
  stage: deploy
  script:
    - "curl -X POST -F token=eb76bc2f8009af7005b43bf8f63bb0 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/347/trigger/pipeline" # bug-injector
  only:
    - master
