variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/sel
  tags: ["kubernetes", "cluster"]
  before_script:
    - cp -r $(pwd)/ /root/quicklisp/local-projects/

check-format:
  stage: .pre
  script:
    - git lisp-format

build-manual:
  stage: test
  script:
    - GT=yes make doc

.test-template: &test
  stage: test
  script:
    - LISP=$LISP GT=yes make check

test-sbcl:
  variables:
    LISP: 'sbcl'
  <<: *test

test-ccl:
  variables:
    LISP: 'ccl'
  <<: *test

binary-release:
  stage: build
  artifacts:
    paths:
      - resolve
  script:
    - sbcl --script build.lisp && ccl --load build.lisp
    - mv build resolve

binary-release-deploy:
  stage: deploy
  needs: ['binary-release', 'test-ccl', 'test-sbcl']
  before_script:
    - mkdir -p ~/.ssh
    - ssh-keyscan -H download-updater.grammatech.com >> ~/.ssh/known_hosts
  script:
    - tar czf $CI_PROJECT_NAME.tar.gz $CI_PROJECT_NAME/*
    - tar --list -f $CI_PROJECT_NAME.tar.gz
    - sshpass -p $MNEMO_ARTIFACTS_PASSWORD scp -p $CI_PROJECT_NAME.tar.gz mnemosyne@download-updater.grammatech.com:.
    - 'curl https://download-updater.grammatech.com/mnemosyne/sync-request/ | grep "RESPONSE: ACCEPTED"'
  only:
    - master


dependents:
  stage: deploy
  script:
    - "curl -X POST -F token=eb76bc2f8009af7005b43bf8f63bb0 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/347/trigger/pipeline" # bug-injector
  only:
    - master
