variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/sel
  tags: ["kubernetes", "cluster"]
  before_script:
    - cp -r $(pwd)/ /root/quicklisp/local-projects/

check-format:
  stage: .pre
  script:
    - git lisp-format

build-manual:
  stage: test
  script:
    - GT=yes make doc

.test-template: &test
  stage: test
  script:
    - LISP=$LISP GT=yes make check

test-sbcl:
  variables:
    LISP: 'sbcl'
  <<: *test

test-ccl:
  variables:
    LISP: 'ccl'
  <<: *test

binary-release:
  stage: deploy
  artifacts:
    paths:
      - resolve
  script:
    - rm -f /tmp/$(basename $LOCAL_IMAGE_NAME).cid
    - docker run --cidfile=/tmp/$(basename $LOCAL_IMAGE_NAME).cid $LOCAL_IMAGE_NAME /bin/bash -c "sbcl --script build.lisp && ccl --load build.lisp"
    - docker cp $(cat /tmp/$(basename $LOCAL_IMAGE_NAME).cid):/root/quicklisp/local-projects/resolve/build resolve
    - rm -f /tmp/$(basename $LOCAL_IMAGE_NAME).cid

dependents:
  stage: deploy
  script:
    - "curl -X POST -F token=eb76bc2f8009af7005b43bf8f63bb0 -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/347/trigger/pipeline" # bug-injector
  only:
    - master
