ARG REF=master
ARG LISP=sbcl
FROM docker.grammatech.com/synthesis/sel/arch-${LISP}:${REF}

RUN pacman -Sy  --noconfirm archlinux-keyring
RUN pacman -Syu --noconfirm expect

COPY . /root/quicklisp/local-projects/resolve
WORKDIR /root/quicklisp/local-projects/resolve

ARG GT
ARG REPORT
ENV PATH=/root/quicklisp/local-projects/resolve/bin:$PATH
RUN make
CMD /bin/bash
