ARG REF
ARG LISP
FROM docker.grammatech.com/synthesis/sel/arch-${LISP:-sbcl}:${REF:-master}

RUN pacman -Sy  --noconfirm archlinux-keyring
RUN pacman -Syu --noconfirm expect jq

COPY . /root/quicklisp/local-projects/resolve
WORKDIR /root/quicklisp/local-projects/resolve

ARG GT
ARG REPORT
ENV PATH=/root/quicklisp/local-projects/resolve/bin:$PATH \
    LISP_HEAP=129024
RUN make
CMD /bin/bash
