ARG REF
ARG LISP
FROM docker.grammatech.com/synthesis/sel/ubuntu-${LISP:-sbcl}:${REF:-master}

RUN apt-get -y update && apt-get -y install python3 expect curl jq

COPY . /root/quicklisp/local-projects/resolve
WORKDIR /root/quicklisp/local-projects/resolve

ARG GT
ARG REPORT
ENV PATH=/usr/synth/bin:/root/quicklisp/local-projects/resolve/bin:$PATH \
    LISP_HEAP=129024 \
    LISP_STACK=128
RUN make
CMD /bin/bash
