ARG REF=docker.grammatech.com/synthesis/resolve/ubuntu-sbcl
FROM $REF as resolve
RUN cd /root/quicklisp/local-projects/resolve && make doc

FROM docker.grammatech.com/synthesis/sel/ubuntu

RUN mkdir -p /root/quicklisp/local-projects/resolve/exp/benchmark

# # Checkout all C/C++ benchmarks.
# RUN cd /root/quicklisp/local-projects/resolve/exp/benchmark && \
#     for bench in acorn grep grep-single-file file leafnode lighttpd memcached morgan mosh nginx openvpn pks proftpd redis sqlite unrealircd wireshark zlib;do \
#         git clone  https://git.grammatech.com/benchmark/${bench}.git; \
#     done

# Checkout all JavaScript benchmarks.
RUN cd /root/quicklisp/local-projects/resolve/exp/benchmark && \
    for bench in yargs underscore tslib through2 rxjs request prop-types node-uuid node-glob node-fs-extra moment minimist generator express commander.js colors.js classnames chalk body-parser bluebird axios async;do \
        git clone https://git.grammatech.com/benchmark/${bench}.git; \
    done

# Ensure we get *all* of the shared libraries.
COPY --from=resolve /usr /usr

# Install requirement tools and additional desirable tools.
RUN apt-get -y update && \
    apt-get -y install python3 expect curl wget nano vim emacs-nox git subversion kdiff3 ack-grep silversearcher-ag screen tmux

COPY --from=resolve /root/quicklisp/local-projects/resolve/bin /root/quicklisp/local-projects/resolve/bin
COPY --from=resolve /root/quicklisp/local-projects/resolve/doc /root/quicklisp/local-projects/resolve/doc
COPY --from=resolve /root/quicklisp/local-projects/resolve/test /root/quicklisp/local-projects/resolve/test
COPY --from=resolve /root/quicklisp/local-projects/resolve/exp /root/quicklisp/local-projects/resolve/exp
COPY --from=resolve /root/.cache /root/.cache

WORKDIR /root/quicklisp/local-projects/resolve/exp

ENV PATH=/root/quicklisp/local-projects/resolve/bin:/root/quicklisp/local-projects/resolve/exp/bin:$PATH
CMD /bin/bash
