variables:
  DOCKER_REGISTRY: "docker.grammatech.com"
  LOCAL_IMAGE_NAME: '$CI_PROJECT_PATH-$CI_BUILD_REF_NAME-$CI_PIPELINE_ID'

before_script:

stages:
  - build
  - test-and-tag
  - deploy-and-cleanup

.build-template: &build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    - docker pull $DOCKER_REGISTRY/synthesis/sel/${OS}
    - docker build --build-arg=GT=yes -f .ci/Dockerfile.${OS} -t ${LOCAL_IMAGE_NAME}-${OS}-${LISP} .
    - if [ ! "$CI_BUILD_REF_NAME" = "latest" ];
      then
          docker tag ${LOCAL_IMAGE_NAME}-${OS}-${LISP} $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS}-${LISP}:${CI_BUILD_REF_NAME};
          docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY;
          docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS}-${LISP}:${CI_BUILD_REF_NAME};
      fi

build-ubuntu-ccl:
  stage: build
  variables:
    OS: 'ubuntu'
    LISP: 'ccl'
  <<: *build

build-ubuntu-sbcl:
  stage: build
  variables:
    OS: 'ubuntu'
    LISP: 'sbcl'
  <<: *build

build-arch-ccl:
  stage: build
  variables:
    OS: 'arch'
    LISP: 'ccl'
  <<: *build

build-arch-sbcl:
  stage: build
  variables:
    OS: 'arch'
    LISP: 'sbcl'
  <<: *build

.run-template: &run
  script:
    # If on master branch, push test results to DataManager and push
    # up a new "latest" image, otherwise, run locally.
    - if [ "$CI_BUILD_REF_NAME" = "master" ];
      then
          docker run -e LOCAL_USER=root -e GT=yes -e REPORT=yes ${LOCAL_IMAGE_NAME}-${OS}-${LISP} /bin/bash -c "cd /root/quicklisp/local-projects/auto-merge && make check bin-check doc";
          if [ "$LISP" = "ccl" ];
          then
              docker tag ${LOCAL_IMAGE_NAME}-${OS}-${LISP} $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS};
              docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY;
              docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS};
          fi
      else
          docker run -e LOCAL_USER=root -e GT=yes ${LOCAL_IMAGE_NAME}-${OS}-${LISP} /bin/bash -c "cd /root/quicklisp/local-projects/auto-merge && unbuffer make check doc";
      fi

run-ubuntu-ccl:
  stage: test-and-tag
  variables:
    OS: 'ubuntu'
    LISP: 'ccl'
  <<: *run

run-ubuntu-sbcl:
  stage: test-and-tag
  variables:
    OS: 'ubuntu'
    LISP: 'sbcl'
  <<: *run

run-arch-ccl:
  stage: test-and-tag
  variables:
    OS: 'arch'
    LISP: 'ccl'
  <<: *run

run-arch-sbcl:
  stage: test-and-tag
  variables:
    OS: 'arch'
    LISP: 'sbcl'
  <<: *run

pages:
  stage: deploy-and-cleanup
  script:
    - export CONTAINER_FILE=${LOCAL_IMAGE_NAME}-arch-sbcl.container
    - mkdir -p $(dirname ${CONTAINER_FILE})
    - docker run -e LOCAL_USER=root -e GT=yes --cidfile=${CONTAINER_FILE} ${LOCAL_IMAGE_NAME}-arch-sbcl /bin/bash -c "mkdir -p /public && cd /root/quicklisp/local-projects/auto-merge && make doc && cp -R doc/auto-merge/* /public/"
    - docker cp $(cat ${CONTAINER_FILE}):/public ./
    - docker rmi -f ${LOCAL_IMAGE_NAME}-arch-ccl
    - docker rmi -f ${LOCAL_IMAGE_NAME}-arch-sbcl
    - docker rmi -f ${LOCAL_IMAGE_NAME}-ubuntu-ccl
    - docker rmi -f ${LOCAL_IMAGE_NAME}-ubuntu-sbcl
  artifacts:
    paths:
      - public
  only:
    - master

cleanup:
  stage: deploy-and-cleanup
  script:
    - docker rmi -f ${LOCAL_IMAGE_NAME}-arch-ccl
    - docker rmi -f ${LOCAL_IMAGE_NAME}-arch-sbcl
    - docker rmi -f ${LOCAL_IMAGE_NAME}-ubuntu-sbcl
    - docker rmi -f ${LOCAL_IMAGE_NAME}-ubuntu-ccl
  except:
    - master
